name: Makefile

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Make
      run: |
        chmod +X make.sh
        ./make.sh
